/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eb2fXCPJ1gl
 */
import { Footer } from "./sections/layout/footer";
import { SuccessStories } from "./sections/CMS/success-stories";
import { Customers } from "./sections/CMS/customers";
import { Features, Features2 } from "./sections/CMS/features";
import { NewsLetter } from "./sections/CMS/newsletter";
import { Hero } from "./sections/CMS/hero";
import { Header } from "./sections/layout/header";

export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <Header />
      <main className="flex-1">
        <Hero />
        <Features />
        <NewsLetter />
        <Features2 />
        <Customers />
        <SuccessStories />
      </main>
      <Footer />
    </div>
  );
}
