import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });
import { notFound } from "next/navigation";
import { unstable_setRequestLocale } from "next-intl/server";
import { Toaster } from "@/components/ui/toaster";
import { MainNav } from "../../components/MainNav";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Can be imported from a shared config
const locales = ["en", "fr"];

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale as any)) notFound();
  // unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <header>
          <Header />
        </header>
        <div className="flex w-full h-full  mx-auto">
          <nav >
            <MainNav className="h-auto" />
          </nav>
          <main className="flex-1 h-auto bg-gray-100">{children}</main>
          <Toaster /> 
        </div>
      </body>
    </html>
  );
}
